import { type DocOptions, splitUrl } from "./util";

/**
 * Browser cookie jar in Netscape `cookies.txt` format — the shape curl, wget,
 * yt-dlp and every "export cookies" extension read and write.
 *
 * This is the highest-value file on a compromised desktop: session cookies are
 * what infostealers are actually there for, because a stolen cookie skips MFA
 * entirely. A jar is therefore both the thing an intruder grabs first and the
 * thing they are most likely to *replay* rather than merely read.
 *
 * The bait entry is scoped to the trigger URL's exact path, so a replay against
 * the canary registers as a hit. Everything else in the file is decoration that
 * makes the jar look lived-in — a one-line cookies.txt is not a cookie jar.
 */
export function generateCookies(opts: DocOptions): Promise<Buffer> {
  const { host, path, secure } = splitUrl(opts.url);
  // Netscape jars store expiry as a Unix timestamp. Fixed rather than
  // now-relative so the same key downloaded twice yields identical bytes.
  const soon = 1_924_905_600; // 2031-01-01
  const later = 1_956_528_000; // 2032-01-01

  const rows: string[][] = [
    // domain, includeSubdomains, path, secure, expiry, name, value
    [".atlassian.net", "TRUE", "/", "TRUE", String(soon), "cloud.session.token", "eyJraWQiOiJzZXNzaW9uLXNlcnZpY2UvcHJvZCJ9"],
    [".okta.com", "TRUE", "/", "TRUE", String(soon), "sid", "102Xk9fQpLmVn3RtYuIoP4aSdF"],
    [".github.com", "TRUE", "/", "TRUE", String(later), "user_session", "8Kd0pQzRxV2mNbC7hJlA3sWe"],
    ["vpn.internal.example.com", "FALSE", "/", "TRUE", String(soon), "SESSIONID", "b41f9c2e77a04e1d8f3b6a90c2d5e814"],
    // The bait: path-scoped to the canary so a replayed jar hits it exactly.
    [host, "FALSE", path, secure ? "TRUE" : "FALSE", String(later), "mantis_session", "s%3A9f2c1b7e4a86d035.7Qk1YxZ0"],
  ];

  const body = [
    "# Netscape HTTP Cookie File",
    "# https://curl.se/docs/http-cookies.html",
    "# This file was generated by libcurl! Edit at your own risk.",
    "",
    ...rows.map((r) => r.join("\t")),
    "",
  ].join("\n");

  return Promise.resolve(Buffer.from(body, "utf8"));
}
